# conf/setattn.yaml
defaults:
  - base

out_dir: out-copy/tmp
eval_interval: 250
eval_iters: 200
log_interval: 50
always_save_checkpoint: false

wandb:
  log: false
  project: setattn-copy
  run_name: copy

data:
  dataset: copy
  training_length: 50
  training_randomize: true
  gradient_accumulation_steps: 1
  batch_size: 1024
  test: true
  test_length: 50
  test_randomize: false
  test_samples: 1000
  
model:
  n_layer: 4
  n_head: 4
  n_embd: 64
  dropout: 0.2
  block_size: 256

optim:
  learning_rate: 1e-3
  max_iters: 20000
  lr_decay_iters: 5000
  min_lr: 1e-4
  beta2: 0.99

lr_decay:
  warmup_iters: 100

attn:
  type: setattn_linear  
  level: 1
  levelmax: 5
  levelrand: true
  k_mapping: False
  v_mapping: False
  smaller_sets: False