out_dir: out-copy

data:
  dataset: copy
  training_length: 20
  randomize: False
  gradient_accumulation_steps: 1
  batch_size: 1
  samples: 10
attn:
  type: vanilla  
  level: 1
  levelrand: false
  levelmax: 4
  k_mapping: False
  v_mapping: False
  smaller_sets: False