# conf/setattn.yaml
defaults:
  - base

out_dir: out-shakespeare-char
eval_interval: 250
eval_iters: 200
log_interval: 100
always_save_checkpoint: false

wandb:
  log: false
  project: fixattn
  run_name: mini-gpt

data:
  dataset: parity
  training_length: 10
  randomize: true
  gradient_accumulation_steps: 1
  batch_size: 512
  block_size: 256

model:
  n_layer: 3
  n_head: 3
  n_embd: 48
  dropout: 0.2

optim:
  learning_rate: 1e-3
  max_iters: 50000
  lr_decay_iters: 5000
  min_lr: 1e-4
  beta2: 0.99

lr_decay:
  warmup_iters: 100

attn:
  type: fixsetlinear  
  set_number: 1
  set_policy: bfs
  set_aggr: linear